syntax = "proto3";
package site.yuanzhou.grpc;
option java_multiple_files = true;
option java_package = "site.yuanzhou.proto";
option java_outer_classname = "NoticeGrpcService";
import "google/protobuf/empty.proto";

message NoticeGrpcDTO {
  string content = 1;
  string from = 2;
  string to = 3;
  int64 type = 4;
}

message MailGrpcDTO {
  string content = 1;
  optional string from = 2;
  optional string to = 3;
  optional int32 type = 4;
  string subject = 5;
}

message WechatGrpcDTO {
  string content = 1;
  string from = 2;
  string to = 3;
  int64 type = 4;
}

service NoticeService {
  rpc sendMailNotice(MailGrpcDTO) returns (google.protobuf.Empty);
  rpc sendNotice(NoticeGrpcDTO) returns (google.protobuf.Empty);
  rpc sendWechatNotice(WechatGrpcDTO) returns (google.protobuf.Empty);
}