quarkus:
  rest-client:
    gotify-api:
      url: ${NOTICE_URL}
      logging:
        scope: request-response
  http:
    root-path: /api
  application:
    name: "notiflow-native"
  mailer:
    host: smtp.resend.com
    username: resend
    password: ${MAIL_RESEND_TOKEN}
    port: 587
notiflow:
  gotify:
    token: ${GOTIFY_TOKEN}